# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- integration

pool: Default

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: Test

  - stage: Deploy_US1
    displayName: US1
    dependsOn: Test
    jobs:
      - job: A

  - stage: Deploy_US2
    displayName: US2
    dependsOn: Test
    jobs:
      - job: B

  - stage: Deploy_Europe
    displayName: Deploy Europe
    dependsOn:
      - Deploy_US1
      - Deploy_US2
    jobs:
      - job: C



