trigger: none

pool: Default

stages:
  - stage: A
    displayName: 'QA'
    jobs:
      - job: A
        steps:
         - task: PowerShell@1
           inputs:
             scriptType: 'inlineScript'
             inlineScript: 'Write-Host "Hello Word"'
             failOnStandardError: false
